version: '3.7'
networks:
  my-network:
    driver: bridge
services:
  server:
    build: .
    depends_on:
      mongo:
        condition: service_started
    command: ["yarn", "start"]
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    networks:
      - my-network
    # restart: always
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_cont:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks:
      - my-network
    # restart: always
volumes:
  mongodb_data_cont: